name: Package Application with Pyinstaller

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Package Application
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: .

      - name: Compress files
        run: |
          cd dist/windows
          zip -r9 Sexy-eGirls-Downloader-${{ github.run_number }}.zip *

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        id: upload-artifact
        with:
          name: Sexy-eGirls-Downloader-${{ github.run_number }}
          path: dist/windows/Sexy-eGirls-Downloader-${{ github.run_number }}.zip
